# Generated by Django 3.0.2 on 2020-04-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('population', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('active', models.IntegerField()),
                ('new_confirmed', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('new_recovered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CovidIndia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('statecode', models.CharField(max_length=5)),
                ('active', models.IntegerField()),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
            ],
        ),
    ]
